# InventorySQL config - by ThisIsAreku - http://dev.bukkit.org/server-mods/inventorysql/
check-interval: 600
check-plugin-updates: true
multiworld: true
allow-unsafe-ench: false
mirror-mode: false
use-permissions: false
gamemode:
  - SURVIVAL
#  - CREATIVE
  - ADVENTURE
mysql:
  host: localhost:3306
  user: root
  pass: pass
  db: minecraft
  table-prefix: invsql
  pool-size: 3
backup:
  enabled: true
  cleanup-days: 5
messages:
  no-modif: '你什么变化都没发现'
  modif: '增加了 %s 物品, %s 物品从 %s 中移除'
  no-online: '没有玩家在线..'
  check-n-players: '检查 %s player(s)'
  check-all-players: '检查 all players...'
  check-yourself: '检查 yourself...'
  mirror-wait: '等等 %s，系统正在准备你的装备..'
  mirror-latest: '检查好装备了 !'
  mirror-done: '信息同步完毕'
update-events:
  join: true
  quit: true
  changeworld: true
  respawn: true
  bedenter: true
  bedleave: true
  death: true
debug: false