name: InventorySQL
main: fr.areku.InventorySQL.InventorySQL
author: ThisIsAreku
website: http://areku.fr/
version: 2.5.4
description: 物品数据化储存
softdepend: [Authenticator, Vault]
commands:
    inv:
        description: InventorySQL - 主要指令
        usage: /inv help
    ichk:
        description: InventorySQL - 检查物品栏
        usage: /ichk
permissions:
  invsql.*:
    description: '全部权限'
    children:
      invsql.check.me: true
      invsql.check.others: true
      invsql.check: true
      invsql.pw: true
      invsql.reload: true
  invsql.pw:
    description: '能改变密码'
    default: true
  invsql.reload:
    description: '能重新加载插件'
    default: op
  invsql.check:
    description: '能检查所有的仓库'
    children:
      invsql.check.me: true
      invsql.check.others: true
  invsql.check.me:
    description: '能检查自己的仓库'
    default: true
  invsql.check.others:
    description: '能检查别人的仓库'
    default: op
    children:
      invsql.check.me: true
  invsql.debug:
    description: '能使用 /inv debug'
    default: op
  invsql.hidemessages:
    description: '隐藏所有提示信息'
    default: false
